###
# this is a valid in-place variable syntax
@myhost = httpbin.org

###
# get ip
GET https://jmarkin.ru/ip

###
GET https://{{myhost}}/json

###
GET https://{{myhost}}/uuid


###
GET https://{{myhost}}/html

###
GET ya.ru



###

GET http://example.com
